URL=window.URL||window.webkitURL;var gumStream;var rec;var input;var AudioContext=window.AudioContext||window.webkitAudioContext;var audioContext
var recordButton=document.getElementById("recordButton");var stopButton=document.getElementById("stopButton");var pauseButton=document.getElementById("pauseButton");var fd=new FormData();const uploadFile=document.querySelector('#uploadFile');uploadFile.addEventListener("click",()=>{uploadAudio();});$("#uploadFile").prop("disabled",true);recordButton.addEventListener("click",startRecording);stopButton.addEventListener("click",stopRecording);pauseButton.addEventListener("click",pauseRecording);var sec=0;function pad(val){return val>9?val:"0"+val;}
var func;function timerstart(){func=setInterval(function(){$("#seconds").html(pad(++sec%60));$("#minutes").html(pad(parseInt(sec/60,10)));},1000);}
function myStopFunction(){clearInterval(func);}
function startRecording(){$("#recordingsList").empty();console.log("recordButton clicked");var constraints={audio:true,video:false}
recordButton.disabled=true;stopButton.disabled=false;pauseButton.disabled=false
navigator.mediaDevices.getUserMedia(constraints).then(function(stream){console.log("getUserMedia() success, stream created, initializing Recorder.js ...");audioContext=new AudioContext();gumStream=stream;input=audioContext.createMediaStreamSource(stream);rec=new Recorder(input,{numChannels:1})
rec.record()
$("#seconds").html("00");$("#minutes").html("00");sec=0;timerstart();$("#uploadFile").prop("disabled",true);console.log("Recording started");}).catch(function(err){recordButton.disabled=false;stopButton.disabled=true;pauseButton.disabled=true});}
function pauseRecording(){console.log("pauseButton clicked rec.recording=",rec.recording);if(rec.recording){rec.stop();pauseButton.innerHTML="Resume";myStopFunction();}else{rec.record()
pauseButton.innerHTML="Pause";timerstart();}}
function stopRecording(){console.log("stopButton clicked");stopButton.disabled=true;recordButton.disabled=false;pauseButton.disabled=true;pauseButton.innerHTML="Pause";rec.stop();myStopFunction();gumStream.getAudioTracks()[0].stop();rec.exportWAV(createDownloadLink);$("#uploadFile").prop("disabled",false);}
function beforeSend(){document.getElementById("audioError").innerHTML="<span style='color: green;'>Please wait...</span>";}
function createDownloadLink(blob){$("#recordingsList").empty();console.log(recordingsList);var url=URL.createObjectURL(blob);var au=document.createElement('audio');var li=document.createElement('li');var user_id=document.getElementById('UserID').value;var filename=new Date().toISOString()+'.wav';au.controls=true;au.src=url;li.appendChild(au);fd.append("soundBlob",blob,filename);li.appendChild(document.createTextNode(" "))
recordingsList.appendChild(li);}
function uploadAudio(){var login_user_role=$("#login_user_role").val();var table_type=$("#table_type").val();var mobile_number=$("#mobile_number").val();var login_user_id=$("#login_user_id").val();var merchant_id=$("#m_id").val();var section_type=$("#section_type").val();var location=$("#mapSearch").val();var section_type=$("#section_type").val();fd.append('table_type',table_type);fd.append('login_user_role',login_user_role);fd.append('login_user_id',login_user_id);fd.append('mobile_number',mobile_number);fd.append('m_id',merchant_id);fd.append('location',location);fd.append('section_type',section_type);$.ajax({type:'POST',url:'upload.php',data:fd,cache:false,contentType:false,processData:false,beforeSend:function()
{$("#spin").show();},}).done(function(data){var returnedData=JSON.parse(data);if(returnedData.error==true){$('#voice_recognition').modal('hide');swal("Your Order Placed.",returnedData.message,"success");setTimeout(function(){if(returnedData.user_type==1){window.location.href='voiceorderlist.php';}else if(returnedData.user_type==2){window.location.href='voiceorderview.php';}else{window.location.href='voiceorderlist.php';}},1000);}else{swal("Error!",returnedData.message,"warning");}},2000);}